### ISSUE TITLE
Embed media content

### ISSUE THREAD

**Issue by irenenikk** [irenenikk/remember-me-front#12]
Should we embed a page preview of blogposts? [like this](https://stackoverflow.com/questions/2117046/how-to-show-live-preview-in-a-small-popup-of-linked-page-on-mouse-over-on-link)

We could also embed videos if they're hosted by youtube or vimeo with the iframe -tag. In yt replace `watch?v=` with `embed/` in url, in vimeo add `player` (as in player.vimeo.com) and add `/video/` before video id in url.

**Comment by TainaLepisto** [comment]
Yes! I was thinking the same, but not for this version. Maybe the next one, if the customer wants it too?

**Comment by TainaLepisto** [comment]
This is on on backlog and sprint log. 

Feature added in 996f751
